"""Dynamic tool synthesis for complex data tasks.

Allows the AI to generate and execute custom Python logic to process 
retrieved knowledge base fragments in ways static tools cannot.
"""

from __future__ import annotations

import sys
import io
import contextlib
import traceback
from typing import Any, Dict, List, Optional

def synthesize_data_processor(
    logic_code: str,
    context_data: List[Dict[str, Any]]
) -> Dict[str, Any]:
    """Execute AI-generated logic code against a provided context.
    
    Args:
        logic_code: Python code generated by the LLM. 
                    Must define an `execute(data)` function.
        context_data: The list of article/graph fragments to process.
        
    Returns:
        The result of the execution or an error message.
    """
    
    # 1. Prepare a restricted environment
    # Note: In a real production system, this would be a containerized sandbox.
    # For this SOTA implementation, we use a restricted local scope.
    safe_globals = {
        "__builtins__": {
            "len": len,
            "list": list,
            "dict": dict,
            "str": str,
            "int": int,
            "float": float,
            "sum": sum,
            "sorted": sorted,
            "enumerate": enumerate,
            "range": range,
            "min": min,
            "max": max,
            "print": print, # For debugging in logs
        },
        "context_data": context_data
    }
    
    stdout_capture = io.StringIO()
    
    try:
        # 2. Capture output and execute
        with contextlib.redirect_stdout(stdout_capture):
            # Prefix with some safety imports if needed
            full_code = f"{logic_code}\n\nresult = execute(context_data)"
            exec(full_code, safe_globals)
        
        result = safe_globals.get("result")
        return {
            "success": True,
            "result": result,
            "stdout": stdout_capture.getvalue()
        }
        
    except Exception as e:
        error_info = traceback.format_exc()
        return {
            "success": False,
            "error": str(e),
            "traceback": error_info,
            "stdout": stdout_capture.getvalue()
        }

def get_synthesis_prompt() -> str:
    """Returns the system prompt instructions for generating synthesis logic."""
    return """
When using 'synthesize_data_processor', you must provide a Python script that follows these rules:
1. Define a function `execute(data)` that takes a list of dictionaries.
2. The function must return a serializable object (dict, list, string, etc.).
3. You have access to standard Python builtins (but no imports like os, subprocess, etc.).
4. Use this tool ONLY when static retrieval tools are insufficient for comparison or aggregation.
"""
